version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/javaapp/

hooks:
  BeforeInstall:
    - location: scripts/stop.sh
      timeout: 60
  Install:
    - location: scripts/clean.sh
      timeout: 60
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 60
