#version: 0.2

#phases:
#  install:
#    runtime-versions:
#      java: corretto11
#  pre_build:
#    commands:
#      - echo Nothing to do in the pre_build phase...
#  build:
#    commands:
#      - echo Build started on `date`
#      - mvn install
#  post_build:
#    commands:
#      - echo Build completed on `date`
#artifacts:
#  files:
#    - target/messageUtil-1.0.jar
version: 0.2

env:
  variables:
    IMAGE_REPO_NAME: "messageutil-repo"
    IMAGE_TAG: "latest"

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo Installing Maven...
      - mvn --version

  pre_build:
    commands:
      - echo Logging into Amazon ECR...
      - aws --version
      - ACCOUNT_ID=$(aws sts get-caller-identity --query "Account" --output text)
      - REGION=$AWS_DEFAULT_REGION
      - REPOSITORY_URI="$ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/$IMAGE_REPO_NAME"
      - aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $REPOSITORY_URI

  build:
    commands:
      - echo Running Maven Tests...
      - mvn test
      - echo Building JAR...
      - mvn package
      - echo Building Docker Image...
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $REPOSITORY_URI:$IMAGE_TAG

  post_build:
    commands:
      - echo Pushing Docker Image to ECR...
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Build completed successfully!

artifacts:
  files:
    - target/messageUtil-1.0.jar
